import 'package:flutter/material.dart';
import 'package:flutterapp/oneapp/generatedloginwidget1/generated/GeneratedFacebooklogologowebsiteicon13201905026259263462Widget.dart';
import 'package:flutterapp/oneapp/generatedloginwidget1/generated/GeneratedGoogleLogo2Widget.dart';
import 'package:flutterapp/oneapp/generatedloginwidget1/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/oneapp/generatedloginwidget1/generated/GeneratedRectangle27Widget1.dart';
import 'package:flutterapp/oneapp/generatedloginwidget1/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/oneapp/generatedloginwidget1/generated/GeneratedForgotPasswordWidget.dart';
import 'package:flutterapp/oneapp/generatedloginwidget1/generated/GeneratedEmailWidget1.dart';
import 'package:flutterapp/oneapp/generatedloginwidget1/generated/GeneratedEllipse13Widget.dart';
import 'package:flutterapp/oneapp/generatedloginwidget1/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/oneapp/generatedloginwidget1/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/oneapp/generatedloginwidget1/generated/GeneratedMaskGroupWidget2.dart';
import 'package:flutterapp/oneapp/generatedloginwidget1/generated/GeneratedLoginWidget2.dart';
import 'package:flutterapp/oneapp/generatedloginwidget1/generated/GeneratedSignUpWidget2.dart';
import 'package:flutterapp/oneapp/generatedloginwidget1/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/oneapp/generatedloginwidget1/generated/GeneratedMaskGroupWidget3.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedHomeScreenWidget'),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(3.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(3.0),
                child: Container(
                  color: Color.fromARGB(255, 202, 233, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedMaskGroupWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedMaskGroupWidget3(),
              ),
              Positioned(
                left: 29.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 59.0,
                child: GeneratedRectangle27Widget1(),
              ),
              Positioned(
                left: 29.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 59.0,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 58.0,
                child: GeneratedEllipse11Widget(),
              ),
              Positioned(
                left: 101.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 58.0,
                child: GeneratedEllipse12Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 49.0,
                child: GeneratedGoogleLogo2Widget(),
              ),
              Positioned(
                left: 106.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 58.0,
                child:
                    GeneratedFacebooklogologowebsiteicon13201905026259263462Widget(),
              ),
              Positioned(
                left: 119.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 87.0,
                child: GeneratedLoginWidget2(),
              ),
              Positioned(
                left: 56.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 28.0,
                child: GeneratedPasswordWidget1(),
              ),
              Positioned(
                left: 56.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 19.0,
                child: GeneratedEmailWidget1(),
              ),
              Positioned(
                left: 275.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedEllipse13Widget(),
              ),
              Positioned(
                left: 169.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 20.0,
                child: GeneratedSignUpWidget2(),
              ),
              Positioned(
                left: 141.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 17.0,
                child: GeneratedForgotPasswordWidget(),
              )
            ]),
      ),
    ));
  }
}
