import 'package:flutter/material.dart';
import 'package:flutterapp/oneapp/generatedlandingpage3widget/generated/GeneratedRectangle32Widget1.dart';
import 'package:flutterapp/oneapp/generatedlandingpage3widget/generated/GeneratedUntitleddesign31Widget.dart';

/* Frame Landing Page 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLandingPage3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedLoginWidget1'),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(3.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(3.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 225, 225),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedUntitleddesign31Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 61.0,
                child: GeneratedRectangle32Widget1(),
              )
            ]),
      ),
    ));
  }
}
