import 'package:flutter/material.dart';
import 'package:flutterapp/oneapp/generatedsignupwidget/generated/GeneratedFacebooklogologowebsiteicon13201905026259263461Widget.dart';
import 'package:flutterapp/oneapp/generatedsignupwidget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/oneapp/generatedsignupwidget/generated/GeneratedSignUpWidget1.dart';
import 'package:flutterapp/oneapp/generatedsignupwidget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/oneapp/generatedsignupwidget/generated/GeneratedGoogleLogo1Widget.dart';
import 'package:flutterapp/oneapp/generatedsignupwidget/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/oneapp/generatedsignupwidget/generated/GeneratedEllipse14Widget.dart';
import 'package:flutterapp/oneapp/generatedsignupwidget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/oneapp/generatedsignupwidget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/oneapp/generatedsignupwidget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/oneapp/generatedsignupwidget/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/oneapp/generatedsignupwidget/generated/GeneratedMaskGroupWidget1.dart';

/* Frame SignUp
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUpWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 640.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(3.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(3.0),
              child: Container(
                color: Color.fromARGB(255, 202, 233, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 640.0,
              child: GeneratedMaskGroupWidget1(),
            ),
            Positioned(
              left: 29.0,
              top: 381.0,
              right: null,
              bottom: null,
              width: 302.0,
              height: 59.0,
              child: GeneratedRectangle25Widget(),
            ),
            Positioned(
              left: 29.0,
              top: 460.0,
              right: null,
              bottom: null,
              width: 302.0,
              height: 59.0,
              child: GeneratedRectangle26Widget(),
            ),
            Positioned(
              left: 40.0,
              top: 539.0,
              right: null,
              bottom: null,
              width: 58.0,
              height: 58.0,
              child: GeneratedEllipse9Widget(),
            ),
            Positioned(
              left: 106.0,
              top: 539.0,
              right: null,
              bottom: null,
              width: 58.0,
              height: 58.0,
              child: GeneratedEllipse10Widget(),
            ),
            Positioned(
              left: 52.0,
              top: 543.0,
              right: null,
              bottom: null,
              width: 34.0,
              height: 49.0,
              child: GeneratedGoogleLogo1Widget(),
            ),
            Positioned(
              left: 111.0,
              top: 539.0,
              right: null,
              bottom: null,
              width: 48.0,
              height: 58.0,
              child:
                  GeneratedFacebooklogologowebsiteicon13201905026259263461Widget(),
            ),
            Positioned(
              left: 102.0,
              top: 220.0,
              right: null,
              bottom: null,
              width: 188.0,
              height: 87.0,
              child: GeneratedSignUpWidget1(),
            ),
            Positioned(
              left: 54.0,
              top: 483.0,
              right: null,
              bottom: null,
              width: 87.0,
              height: 28.0,
              child: GeneratedPasswordWidget(),
            ),
            Positioned(
              left: 54.0,
              top: 404.0,
              right: null,
              bottom: null,
              width: 41.0,
              height: 19.0,
              child: GeneratedEmailWidget(),
            ),
            Positioned(
              left: 281.0,
              top: 542.0,
              right: null,
              bottom: null,
              width: 50.0,
              height: 50.0,
              child: GeneratedEllipse14Widget(),
            ),
            Positioned(
              left: 164.0,
              top: 605.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 20.0,
              child: GeneratedLoginWidget(),
            )
          ]),
    ));
  }
}
