import 'package:flutter/material.dart';
import 'package:flutterapp/oneapp/generatedlandingpage2widget/generated/GeneratedUntitleddesign21Widget.dart';
import 'package:flutterapp/oneapp/generatedlandingpage2widget/generated/GeneratedRectangle33Widget.dart';

/* Frame Landing Page 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLandingPage2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedLandingPage3Widget'),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(3.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(3.0),
                child: Container(
                  color: Color.fromARGB(255, 250, 250, 250),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedUntitleddesign21Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 61.0,
                child: GeneratedRectangle33Widget(),
              )
            ]),
      ),
    ));
  }
}
