import 'package:flutter/material.dart';
import 'package:flutterapp/oneapp/generatedforgotpasswordwidget1/generated/GeneratedForgotPasswordWidget2.dart';
import 'package:flutterapp/oneapp/generatedforgotpasswordwidget1/generated/GeneratedRectangle29Widget1.dart';
import 'package:flutterapp/oneapp/generatedforgotpasswordwidget1/generated/GeneratedEmailWidget2.dart';
import 'package:flutterapp/oneapp/generatedforgotpasswordwidget1/generated/GeneratedMaskGroupWidget4.dart';
import 'package:flutterapp/oneapp/generatedforgotpasswordwidget1/generated/GeneratedEllipse14Widget1.dart';

/* Frame ForgotPassword
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedForgotPasswordWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedHomeScreenWidget'),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(3.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(3.0),
                child: Container(
                  color: Color.fromARGB(255, 202, 233, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedMaskGroupWidget4(),
              ),
              Positioned(
                left: 29.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 59.0,
                child: GeneratedRectangle29Widget1(),
              ),
              Positioned(
                left: 50.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 19.0,
                child: GeneratedEmailWidget2(),
              ),
              Positioned(
                left: 136.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 16.0,
                child: GeneratedForgotPasswordWidget2(),
              ),
              Positioned(
                left: 281.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedEllipse14Widget1(),
              )
            ]),
      ),
    ));
  }
}
