import 'package:flutter/material.dart';
import 'package:flutterapp/oneapp/generatedhomescreenwidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/oneapp/generatedhomescreenwidget/generated/GeneratedCreateroomWidget.dart';
import 'package:flutterapp/oneapp/generatedhomescreenwidget/generated/GeneratedAPPNAMEWidget.dart';
import 'package:flutterapp/oneapp/generatedhomescreenwidget/generated/GeneratedEllipse7Widget.dart';
import 'package:flutterapp/oneapp/generatedhomescreenwidget/generated/GeneratedRectangle13Widget.dart';

/* Frame HomeScreen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 640.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(3.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(3.0),
              child: Container(
                color: Color.fromARGB(255, 68, 63, 63),
              ),
            ),
            Positioned(
              left: 11.0,
              top: 18.0,
              right: null,
              bottom: null,
              width: 338.0,
              height: 605.0,
              child: GeneratedFrame1Widget(),
            ),
            Positioned(
              left: 279.0,
              top: 554.0,
              right: null,
              bottom: null,
              width: 70.0,
              height: 70.0,
              child: GeneratedCreateroomWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 62.0,
              child: GeneratedRectangle13Widget(),
            ),
            Positioned(
              left: 11.0,
              top: 17.0,
              right: null,
              bottom: null,
              width: 122.0,
              height: 30.0,
              child: GeneratedAPPNAMEWidget(),
            ),
            Positioned(
              left: 343.0,
              top: 18.0,
              right: null,
              bottom: null,
              width: 36.0,
              height: 36.0,
              child: GeneratedEllipse7Widget(),
            )
          ]),
    ));
  }
}
