import 'package:flutter/material.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedSettingsWidget2.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedSettingsWidget1.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedSettingsWidget5.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedSettingsWidget3.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedSettingsWidget7.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedEllipse8Widget11.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedSettingsWidget6.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedSettingsWidget4.dart';
import 'package:flutterapp/oneapp/generatedsettingswidget/generated/GeneratedRectangle16Widget.dart';

/* Frame Settings
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedHomeScreenWidget'),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(3.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(3.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 116.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 116.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 58.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 58.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 58.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 58.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 58.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 58.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 58.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 58.0,
                child: GeneratedRectangle22Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 82.0,
                child: GeneratedEllipse8Widget11(),
              ),
              Positioned(
                left: 18.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 33.0,
                child: GeneratedSettingsWidget1(),
              ),
              Positioned(
                left: 106.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 33.0,
                child: GeneratedNameWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 191.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 33.0,
                child: GeneratedSettingsWidget2(),
              ),
              Positioned(
                left: 18.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 33.0,
                child: GeneratedSettingsWidget3(),
              ),
              Positioned(
                left: 18.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 33.0,
                child: GeneratedSettingsWidget4(),
              ),
              Positioned(
                left: 13.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 33.0,
                child: GeneratedSettingsWidget5(),
              ),
              Positioned(
                left: 13.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 33.0,
                child: GeneratedSettingsWidget6(),
              ),
              Positioned(
                left: 13.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 33.0,
                child: GeneratedSettingsWidget7(),
              )
            ]),
      ),
    ));
  }
}
